routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\DonationCategoryController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\DonationStatusController;
use App\Http\Controllers\Backend\MemberController;
use App\Http\Controllers\Backend\DonationController;
use App\Http\Controllers\Backend\DonationDetailsController;
use App\Http\Controllers\Backend\TermsController;
use App\Http\Controllers\Backend\QuantityController;
use App\Http\Controllers\RegionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'role:admin'])
     ->group(function (){
         Route::get('/', [DashboardController::class, 'index']);
         Route::resource('users', UserController::class);
         Route::resource('donationcategory', DonationCategoryController::class);
         Route::resource('role', RoleController::class);
         Route::resource('donationstatus', DonationStatusController::class);
         Route::get('members/get-members/{id}', [MemberController::class, 'getMembers'])->name('getMembers');
         Route::resource('members', MemberController::class);
         Route::post('donation/confirm/{id}', [DonationController::class, 'confirm'])->name('donation.confirm');
         Route::resource('donation', DonationController::class);
         Route::resource('terms', TermsController::class);
         Route::resource('quantity', QuantityController::class);
         Route::get('donation-detail/{id}', [DonationDetailsController::class, 'getDetails'])->name('donation-details');
         Route::get('food/{id}', [DonationDetailsController::class, 'getFood'])->name('get-foods');
         Route::get('food/create/{id}', [DonationDetailsController::class, 'createFood'])->name('create-food');
         Route::post('food/store', [DonationDetailsController::class, 'storeFood'])->name('store-food');
         Route::get('food/edit/{id}', [DonationDetailsController::class, 'editFood'])->name('edit-food');
         Route::put('food/update/{id}', [DonationDetailsController::class, 'updateFood'])->name('update-food');
         Route::delete('food/destroy/{donation_id}/{id}', [DonationDetailsController::class, 'destroyFood'])->name('delete-foods');
         Route::get('regions/province', [RegionController::class, 'getProvinces'])->name('province');
         Route::get('regions/cities/{id}', [RegionController::class, 'getCities'])->name('city');
         Route::get('regions/districts/{id}', [RegionController::class, 'getDistricts'])->name('district');
         Route::get('regions/villages/{id}', [RegionController::class, 'getVillages'])->name('village');
     });



require __DIR__.'/auth.php';

app/Models/Terms.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Terms extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'isi',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
      
    ];
}

app/Http/Controllers/API/TermsController.php
<?php

namespace App\Http\Controllers\API;

use Exception;
use App\Models\Terms;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\API\ResponseFormatter;

class TermsController extends Controller
{
    public function getTerms()
    {
        try {
            $terms = Terms::select('*')->orderBy('id', 'DESC')->first();

            return ResponseFormatter::success($terms, "Data terms berhasil diambil.");
        } catch (Exception $error) {
            return ResponseFormatter::error(null, "Data terms tidak ada.", 404);
        }
    }
}

app/Http/Controllers/Backend/TermsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Terms;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;
use RealRashid\SweetAlert\Facades\Alert;
class TermsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Terms::select('*');
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
     
                        return '<div class="dropdown dropleft">
                                    <button class="btn btn-secondary btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-bars"></i>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="'.route('terms.edit', $row->id).'"><i class="fas fa-pencil-alt"></i> Edit</a>
                                        <form action="'.route('terms.destroy', $row->id).'" method="POST">
                                            '.method_field("DELETE").'
                                            '.csrf_field().'
                                            <button type="submit" class="dropdown-item btn-delete" onclick="return confirm(\'Are You Sure Want to Delete?\')"><i class="fas fa-trash"></i> Delete</button>
                                        </form>
                                    </div>
                                </div>';
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        
        return view('pages.terms.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.terms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make(
            $request->all(),
            [
                'isi' => 'required|string',
            ]
        );
        if($validate->fails()) {
            return back()->with('errors', $validate->messages()->all()[0])->withInput();           
        } else {
            $terms = Terms::create([
                'isi' => $request->isi,
               
            ]);

            if($terms) {
                return redirect()->route('terms.index')->with('success','Terms created successfully.');
            } else {
                return back()->with('errors', 'Terms created failed.');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $terms = Terms::findOrFail($id);

        return view('pages.terms.edit', [
            'item' => $terms,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = Validator::make(
            $request->all(),
            [
                'isi' => 'required|string',
            ]
        );
        if($validate->fails()) {
            return back()->with('errors', $validate->messages()->all()[0])->withInput();           
        } else {
            $data = $request->all();
            $terms = Terms::findOrFail($id);
            $terms->update($data);

            if($terms) {
                return redirect()->route('terms.index')->with('success','Terms updated successfully.');
            } else {
                return back()->with('errors', 'Terms updated failed.');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $terms = Terms::findOrFail($id);
        $terms->delete();
    
        return redirect()->route('terms.index')->with('success','Terms deleted successfully.');
    }
}

resources/views/pages/terms/create.blade.php
@extends('layouts.default')
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Terms</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Terms</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content-header -->
  
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Form Add Terms</h3>
                  </div>
                  <form action="{{ route('terms.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                      <div class="form-group">
                        <label for="isi">Isi <span class="text-danger">*</span></label>
                        <textarea class="form-control summernote" id="isi" name="isi" required>{{ old('isi') }}</textarea>
                      </div>
                    </div>
                    <div class="card-footer">
                      <div class="row">
                        <p><span class="text-danger">*</span> Wajib diisi</p>
                      </div>
                      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Submit</button>
                      <a class="btn btn-warning" href="{{ route('terms.index') }}">
                          <i class="fas fa-arrow-left"></i> Kembali
                      </a>
                    </div>
                  </form>
              </div>
          </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

@endsection

resources/views/pages/terms/edit.blade.php
@extends('layouts.default')
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Terms</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Terms</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content-header -->
  
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Form Edit Terms</h3>
                  </div>
                  <form action="{{ route('terms.update', $item->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card-body">
                      <div class="form-group">
                        <label for="isi">Isi <span class="text-danger">*</span></label>
                        <textarea class="form-control summernote" id="isi" name="isi" required>{{ old('isi') ?? $item->isi }}</textarea>
                      </div>
                    </div>
                    <div class="card-footer">
                      <div class="row">
                        <p><span class="text-danger">*</span> Wajib diisi</p>
                      </div>
                      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Submit</button>
                      <a class="btn btn-warning" href="{{ route('terms.index') }}">
                          <i class="fas fa-arrow-left"></i> Kembali
                      </a>
                    </div>
                  </form>
              </div>
          </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

@endsection

resources/views/pages/terms/index.blade.php
@extends('layouts.default')
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Terms</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Terms</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content-header -->
  
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Terms</h3>
                    <div class="card-tools">
                        <a href="/terms/create" class="btn btn-tool pull-right">
                            <i class="fas fa-plus-square"></i> Add Data
                        </a>
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                  </div>
                  <div class="card-body">
                    <table class="table table-striped table-bordered table-hover table-datatable data-table">
                        <thead>
                            <tr>
                              <th class="text-center" style="width: 1%">#</th>
                              <th class="text-center">Isi</th>
                              <th class="text-center" style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody id="table-data"></tbody>
                    </table>
                  </div>
              </div>
          </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
        
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('terms.index') }}",
                columns: [
                    {
                        data: "DT_RowIndex", 
                        name: "DT_RowIndex", 
                        class: "text-center", 
                        orderable: false, 
                        searchable: false,
                    },
                    {data: 'isi', name: 'isi'},
                    {
                        data: 'action', 
                        name: 'action',
                        class: 'text-center', 
                        orderable: false, 
                        searchable: false,
                    },
                ]
            });
        
        });
    </script>
@endpush