routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\DonationCategoryController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\DonationStatusController;
use App\Http\Controllers\Backend\MemberController;
use App\Http\Controllers\Backend\DonationController;
use App\Http\Controllers\Backend\DonationDetailsController;
use App\Http\Controllers\Backend\TermsController;
use App\Http\Controllers\Backend\QuantityController;
use App\Http\Controllers\RegionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'role:admin'])
     ->group(function (){
         Route::get('/', [DashboardController::class, 'index']);
         Route::resource('users', UserController::class);
         Route::resource('donationcategory', DonationCategoryController::class);
         Route::resource('role', RoleController::class);
         Route::resource('donationstatus', DonationStatusController::class);
         Route::get('members/get-members/{id}', [MemberController::class, 'getMembers'])->name('getMembers');
         Route::resource('members', MemberController::class);
         Route::post('donation/confirm/{id}', [DonationController::class, 'confirm'])->name('donation.confirm');
         Route::resource('donation', DonationController::class);
         Route::resource('terms', TermsController::class);
         Route::resource('quantity', QuantityController::class);
         Route::get('donation-detail/{id}', [DonationDetailsController::class, 'getDetails'])->name('donation-details');
         Route::get('food/{id}', [DonationDetailsController::class, 'getFood'])->name('get-foods');
         Route::get('food/create/{id}', [DonationDetailsController::class, 'createFood'])->name('create-food');
         Route::post('food/store', [DonationDetailsController::class, 'storeFood'])->name('store-food');
         Route::get('food/edit/{id}', [DonationDetailsController::class, 'editFood'])->name('edit-food');
         Route::put('food/update/{id}', [DonationDetailsController::class, 'updateFood'])->name('update-food');
         Route::delete('food/destroy/{donation_id}/{id}', [DonationDetailsController::class, 'destroyFood'])->name('delete-foods');
         Route::get('regions/province', [RegionController::class, 'getProvinces'])->name('province');
         Route::get('regions/cities/{id}', [RegionController::class, 'getCities'])->name('city');
         Route::get('regions/districts/{id}', [RegionController::class, 'getDistricts'])->name('district');
         Route::get('regions/villages/{id}', [RegionController::class, 'getVillages'])->name('village');
     });



require __DIR__.'/auth.php';

app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Member extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'tempat_lahir',
        'tanggal_lahir',
        'no_telp',
        'alamat',
        'provinsi',
        'kota',
        'kecamatan',
        'kelurahan',
        'rt',
        'rw',
        'kode_pos',
        'foto',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
      
    ];
}

app/Http/Controllers/Backend/MemberController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use App\Models\Member;
use Illuminate\Http\Request;
use App\Traits\GeneralTraits;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use RealRashid\SweetAlert\Facades\Alert;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\API\ResponseFormatter;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    use GeneralTraits;
    
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Member::select(['members.*', 'users.name', 'users.email'])
                            ->join('users', 'users.id', '=', 'members.user_id');
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
     
                        return '<div class="dropdown dropleft">
                                    <button class="btn btn-secondary btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-bars"></i>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="'.route('members.show', $row->id).'"><i class="fas fa-eye"></i> View</a>
                                        <a class="dropdown-item" href="'.route('members.edit', $row->id).'"><i class="fas fa-pencil-alt"></i> Edit</a>
                                        <form action="'.route('members.destroy', $row->id).'" method="POST">
                                            '.method_field("DELETE").'
                                            '.csrf_field().'
                                            <button type="submit" class="dropdown-item btn-delete" onclick="return confirm(\'Are You Sure Want to Delete?\')"><i class="fas fa-trash"></i> Delete</button>
                                        </form>
                                    </div>
                                </div>';
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        
        return view('pages.member.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.member.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make(
            $request->all(),
            [
                'name' => 'required|string|max:255',
                'email' => 'required|string|max:255|unique:users',
                'password' => 'required|string|min:8',
                'no_telp' => 'required|string|max:255',
                'foto' => 'image|mimes:jpeg,png,jpg',
            ]
        );
        if ($validate->fails()) {
            return back()->with('errors', $validate->messages()->all()[0])->withInput();
        } else {
            $users = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'password' => Hash::make($request->password),
            ]);

            $users->assignRole('user');

            $members = Member::create([
                'user_id' => $users->id,
                'tempat_lahir' => $request->tempat_lahir,
                'tanggal_lahir' => $request->tanggal_lahir,
                'no_telp' => $request->no_telp,
                'alamat' => $request->alamat,
                'provinsi' => $request->provinsi,
                'kota' => $request->kota,
                'kecamatan' => $request->kecamatan,
                'kelurahan' => $request->kelurahan,
                'rw' => $request->rw,
                'rt' => $request->rt,
                'kode_pos' => $request->kode_pos,
               
            ]);

            
            if ($request->file('foto')) {
                $photo_profile = $request->file('foto');
                $path_profile = '/uploads/images/photo-profile';

                $filename_photo = $this->storeCompressImage($photo_profile, $path_profile);

                $members->update([
                    'foto' => $filename_photo,
                ]);
            }

            if($users && $members) {
                return redirect()->route('members.index')->with('success','Member created successfully.');
            } else {
                return back()->with('errors', 'Member created failed.');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $members = DB::table('members')
                        ->select(
                            'members.*', 
                            'users.name as name', 'users.email as email', 
                            'provinces.name as provinsi', 'regencies.name as kota', 'districts.name as kecamatan', 'villages.name as kelurahan',
                        )
                        ->join('users', 'users.id', '=', 'members.user_id')
                        ->leftJoin('provinces', 'provinces.id', '=', 'members.provinsi')
                        ->leftJoin('regencies', 'regencies.id', '=', 'members.kota')
                        ->leftJoin('districts', 'districts.id', '=', 'members.kecamatan')
                        ->leftJoin('villages', 'villages.id', '=', 'members.kelurahan')
                        ->where('members.id', '=', $id)
                        ->first();

        return view('pages.member.show', [
            'item' => $members,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $members = DB::table('members')
                        ->select(
                            'members.*', 
                            'users.name as name', 'users.email as email', 
                        )
                        ->join('users', 'users.id', '=', 'members.user_id')
                        ->where('members.id', '=', $id)
                        ->first();

        return view('pages.member.edit', [
            'item' => $members,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = Validator::make(
            $request->all(),
            [
                'name' => 'required|string|max:255',
                'email' => 'required|string|max:255',
                'no_telp' => 'required|string|max:255',
                'foto' => 'image|mimes:jpeg,png,jpg',
            ]
        );
        if ($validate->fails()) {
            return back()->with('errors', $validate->messages()->all()[0])->withInput();
        } else {

            $members = Member::findOrFail($id);
            $users = User::findOrFail($members->user_id);
            $users->update([
                'name'  => $request->name,
                'email' => $request->email,
            ]);
           
            $members->update([
                'user_id' => $users->id,
                'tempat_lahir' => $request->tempat_lahir,
                'tanggal_lahir' => $request->tanggal_lahir,
                'no_telp' => $request->no_telp,
                'alamat' => $request->alamat,
                'provinsi' => $request->provinsi,
                'kota' => $request->kota,
                'kecamatan' => $request->kecamatan,
                'kelurahan' => $request->kelurahan,
                'rw' => $request->rw,
                'rt' => $request->rt,
                'kode_pos' => $request->kode_pos,
            ]);

            if($request->password) {
                $users->update([
                    'password' => Hash::make($request->password),
                ]);
            }

            if ($request->file('foto')) {
                $file_path = public_path('/uploads/images/photo-profile/');
                File::delete($file_path.$members->foto);

                $photo_profile = $request->file('foto');
                $path_profile = '/uploads/images/photo-profile';

                $filename_photo = $this->storeCompressImage($photo_profile, $path_profile);

                $members->update([
                    'foto' => $filename_photo,
                ]);
            } 

            if($users && $members) {
                return redirect()->route('members.index')->with('success','Member created successfully.');
            } else {
                return back()->with('errors', 'Member created failed.');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $members = Member::findOrFail($id);
        $users = User::findOrFail($members->user_id);
        $file_path = public_path('/uploads/images/photo-profile/');

        File::delete($file_path.$members->foto);
        $users->delete();
        $members->delete();

        return redirect()->route('members.index')->with('success','Member deleted successfully.');
    }

    public function getMembers($id) {

resources/views/pages/member/create.blade.php
@extends('layouts.default')
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Member</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Member</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content-header -->
  
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Form Tambah Member</h3>
                  </div>
                  <form action="{{ route('members.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                      <div class="form-group">
                        <label for="name">Nama <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter name"  value="{{ old('name') }}" required>
                      </div>
                      <div class="form-group">
                        <label for="email">Email <span class="text-danger">*</span></label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"  value="{{ old('email') }}" required>
                      </div>
                      <div class="form-group">
                        <label for="password">Password <span class="text-danger">*</span></label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"  value="{{ old('password') }}" required>
                      </div>
                      <div class="form-group">
                        <label for="no_telp">No Telp <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="no_telp" name="no_telp" placeholder="Enter no telp" value="{{ old('no_telp') }}" required>
                      </div>
                      <div class="form-group">
                        <label for="tempat_lahir">Tempat Lahir</label>
                        <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="Enter tempat lahir" value="{{ old('tempat_lahir') }}">
                      </div>
                      <div class="form-group">
                        <label for="tanggal_lahir">Tanggal Lahir</label>
                        <div class="input-group date" id="tanggal_lahir" data-target-input="nearest">
                          <input type="text" class="form-control datetimepicker-input" data-target="#tanggal_lahir" id="tanggal_lahir" name="tanggal_lahir" value="{{ old('tanggal_lahir') }}" placeholder="Enter tanggal lahir">
                          <div class="input-group-append" data-target="#tanggal_lahir" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control" id="alamat" name="alamat" placeholder="Enter alamat" value="{{ old('alamat') }}">
                      </div>
                      <div class="form-group">
                        <label for="provinsi">Provinsi</label>
                        <select class="form-control" id="provinsi" name="provinsi" placeholder="Enter provinsi" value="{{ old('provinsi') }}">
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="kota">Kota</label>
                        <select class="form-control" id="kota" name="kota" placeholder="Enter kota" value="{{ old('kota') }}" disabled>
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="kecamatan">Kecamatan</label>
                        <select class="form-control" id="kecamatan" name="kecamatan" placeholder="Enter kecamatan" value="{{ old('kecamatan') }}" disabled>
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="kelurahan">Kelurahan</label>
                        <select class="form-control" id="kelurahan" name="kelurahan" placeholder="Enter kelurahan" value="{{ old('kelurahan') }}" disabled>
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="rw">RW</label>
                        <input type="text" class="form-control" id="rw" name="rw" placeholder="Enter rw" value="{{ old('rw') }}">
                      </div>
                      <div class="form-group">
                        <label for="rt">RT</label>
                        <input type="text" class="form-control" id="rt" name="rt" placeholder="Enter rt" value="{{ old('rt') }}">
                      </div>
                      <div class="form-group">
                        <label for="kode_pos">Kode Pos</label>
                        <input type="text" class="form-control" id="kode_pos" name="kode_pos" placeholder="Enter kode pos" value="{{ old('kode_pos') }}">
                      </div>
                      <div class="form-group">
                        <label for="foto">Foto</label>
                        <div class="custom-file">
                          <input type="file" class="custom-file-input" id="foto" name="foto" placeholder="Enter foto" value="{{ old('foto') }}" accept="image/*">
                          <label class="custom-file-label" for="foto">Choose file</label>
                        </div>
                      </div>
                    </div>
                    <div class="card-footer">
                      <div class="row">
                        <p><span class="text-danger">*</span> Wajib diisi</p>
                      </div>
                      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Submit</button>
                      <a class="btn btn-warning" href="{{ route('members.index') }}">
                          <i class="fas fa-arrow-left"></i> Kembali
                      </a>
                    </div>
                  </form>
              </div>
          </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

@endsection

@push('js')
  <script src="{{ asset('js/backend/member/add_member.js') }}"></script>
@endpush

resources/views/pages/member/edit.blade.php
@extends('layouts.default')
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Member</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Member</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content-header -->
  
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">Form Edit Member</h3>
                  </div>
                  <form action="{{ route('members.update', $item->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card-body">
                      <div class="form-group">
                        <label for="name">Nama <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter name"  value="{{ old('name') ?? $item->name }}" required>
                      </div>
                      <div class="form-group">
                        <label for="email">Email <span class="text-danger">*</span></label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"  value="{{ old('email') ?? $item->email }}" required>
                      </div>
                      <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"  value="{{ old('password') }}">
                      </div>
                      <div class="form-group">
                        <label for="no_telp">No Telp <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="no_telp" name="no_telp" placeholder="Enter no telp" value="{{ old('no_telp') ?? $item->no_telp }}" required>
                      </div>
                      <div class="form-group">
                        <label for="tempat_lahir">Tempat Lahir</label>
                        <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="Enter tempat lahir" value="{{ old('tempat_lahir') ?? $item->tempat_lahir }}">
                      </div>
                      <div class="form-group">
                        <label for="tanggal_lahir">Tanggal Lahir</label>
                        <div class="input-group date" id="tanggal_lahir" data-target-input="nearest">
                          <input type="text" class="form-control datetimepicker-input" data-target="#tanggal_lahir" id="tanggal_lahir" name="tanggal_lahir" value="{{ old('tanggal_lahir') ?? $item->tanggal_lahir}}" placeholder="Enter tanggal lahir">
                          <div class="input-group-append" data-target="#tanggal_lahir" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control" id="alamat" name="alamat" placeholder="Enter alamat" value="{{ old('alamat') ?? $item->alamat }}">
                      </div>
                      <div class="form-group">
                        <label for="provinsi">Provinsi</label>
                        <select class="form-control" id="provinsi" name="provinsi" placeholder="Enter provinsi" value="{{ old('provinsi') ?? $item->provinsi }}">
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="kota">Kota</label>
                        <select class="form-control" id="kota" name="kota" placeholder="Enter kota" value="{{ old('kota') ?? $item->kota }}" disabled>
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="kecamatan">Kecamatan</label>
                        <select class="form-control" id="kecamatan" name="kecamatan" placeholder="Enter kecamatan" value="{{ old('kecamatan') ?? $item->kecamatan }}" disabled>
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="kelurahan">Kelurahan</label>
                        <select class="form-control" id="kelurahan" name="kelurahan" placeholder="Enter kelurahan" value="{{ old('kelurahan') ?? $item->kelurahan }}" disabled>
                          <!-- Generate on javascript -->
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="rw">RW</label>
                        <input type="text" class="form-control" id="rw" name="rw" placeholder="Enter rw" value="{{ old('rw') ?? $item->rw }}">
                      </div>
                      <div class="form-group">
                        <label for="rt">RT</label>
                        <input type="text" class="form-control" id="rt" name="rt" placeholder="Enter rt" value="{{ old('rt') ?? $item->rt }}">
                      </div>
                      <div class="form-group">
                        <label for="kode_pos">Kode Pos</label>
                        <input type="text" class="form-control" id="kode_pos" name="kode_pos" placeholder="Enter kode pos" value="{{ old('kode_pos') ?? $item->kode_pos }}">
                      </div>
                      <div class="form-group">
                        <label for="foto">Foto</label>
                        <div class="row">
                          <div class="col-3">
                            <a id="image-click">
                              <img class="rounded" id="image-resource" src="{{ $item->foto ? asset('/uploads/images/photo-profile/'.$item->foto) : asset('/uploads/images/photo-profile/blank-photo-profile.png') }}" width="250" alt="foto {{ $item->name }}" />
                            </a>
                          </div>
                          <div class="col-9">
                            <div class="custom-file">
                              <input type="file" class="custom-file-input" id="foto" name="foto" placeholder="Enter foto" value="{{ old('foto') ?? $item->foto }}" accept="image/*">
                              <label class="custom-file-label" for="foto">Change picture</label>
                            </div>
                          </div>
                        </div>  
                      </div>
                    </div>
                    <div class="card-footer">
                      <div class="row">
                        <p><span class="text-danger">*</span> Wajib diisi</p>
                      </div>
                      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Submit</button>
                      <a class="btn btn-warning" href="{{ route('members.index') }}">
                          <i class="fas fa-arrow-left"></i> Kembali
                      </a>
                    </div>
                  </form>
              </div>
          </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

@endsection

@push('js')
  <script>
    var domisili = {
      provinsi: "{{ $item->provinsi }}",
      kota: "{{ $item->kota }}",
      kecamatan: "{{ $item->kecamatan }}",
      kelurahan: "{{ $item->kelurahan }}",
    }
  </script>
  <script src="{{ asset('js/backend/member/edit_member.js') }}"></script>
@endpush