routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\DonationCategoryController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\DonationStatusController;
use App\Http\Controllers\Backend\MemberController;
use App\Http\Controllers\Backend\DonationController;
use App\Http\Controllers\Backend\DonationDetailsController;
use App\Http\Controllers\Backend\TermsController;
use App\Http\Controllers\Backend\QuantityController;
use App\Http\Controllers\RegionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'role:admin'])
     ->group(function (){
         Route::get('/', [DashboardController::class, 'index']);
         Route::resource('users', UserController::class);
         Route::resource('donationcategory', DonationCategoryController::class);
         Route::resource('role', RoleController::class);
         Route::resource('donationstatus', DonationStatusController::class);
         Route::get('members/get-members/{id}', [MemberController::class, 'getMembers'])->name('getMembers');
         Route::resource('members', MemberController::class);
         Route::post('donation/confirm/{id}', [DonationController::class, 'confirm'])->name('donation.confirm');
         Route::resource('donation', DonationController::class);
         Route::resource('terms', TermsController::class);
         Route::resource('quantity', QuantityController::class);
         Route::get('donation-detail/{id}', [DonationDetailsController::class, 'getDetails'])->name('donation-details');
         Route::get('food/{id}', [DonationDetailsController::class, 'getFood'])->name('get-foods');
         Route::get('food/create/{id}', [DonationDetailsController::class, 'createFood'])->name('create-food');
         Route::post('food/store', [DonationDetailsController::class, 'storeFood'])->name('store-food');
         Route::get('food/edit/{id}', [DonationDetailsController::class, 'editFood'])->name('edit-food');
         Route::put('food/update/{id}', [DonationDetailsController::class, 'updateFood'])->name('update-food');
         Route::delete('food/destroy/{donation_id}/{id}', [DonationDetailsController::class, 'destroyFood'])->name('delete-foods');
         Route::get('regions/province', [RegionController::class, 'getProvinces'])->name('province');
         Route::get('regions/cities/{id}', [RegionController::class, 'getCities'])->name('city');
         Route::get('regions/districts/{id}', [RegionController::class, 'getDistricts'])->name('district');
         Route::get('regions/villages/{id}', [RegionController::class, 'getVillages'])->name('village');
     });



require __DIR__.'/auth.php';

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Member;
use Illuminate\Http\Request;
use App\Models\DonationHistory;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class DashboardController extends Controller
{
    public function index()
    {
        $menunggu = DonationHistory::join(DB::raw(
                                                    '(SELECT MAX(`id`) as histories_id, donations_id FROM donation_histories GROUP BY donations_id) histories'
                                                ), function($join) {
                                                    $join->on('donation_histories.id', '=', 'histories.histories_id');
                                                })
                                    ->where('donation_statuses_id',1)->count();
        $proses = DonationHistory::join(DB::raw(
                                                    '(SELECT MAX(`id`) as histories_id, donations_id FROM donation_histories GROUP BY donations_id) histories'
                                                ), function($join) {
                                                    $join->on('donation_histories.id', '=', 'histories.histories_id');
                                                })
                                ->where('donation_statuses_id',2)->count();
        $berhasil = DonationHistory::join(DB::raw(
                                                    '(SELECT MAX(`id`) as histories_id, donations_id FROM donation_histories GROUP BY donations_id) histories'
                                                ), function($join) {
                                                    $join->on('donation_histories.id', '=', 'histories.histories_id');
                                                })
                                    ->where('donation_statuses_id',3)->count();
        $members = Member::count();



        return view('pages.dashboard.dashboard', [
            'tunggu' => $menunggu,
            'proses' => $proses, 
            'berhasil' => $berhasil, 
            'members' => $members
        ]);
    }
}

resources/views/pages/dashboard/dashboard.blade.php
@extends('layouts.default')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item active"><a href="/">Dashboard</a></li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">  <!-- menunggu -->
          <div class="inner">
            <h3>{{$tunggu}}</h3>

            <p>Menunggu</p>
          </div>
          <div class="icon">
            <i class="nav-icon fas fa-clock"></i>
          </div>
          <a href="{{ route('donation.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-6"> <!-- proses -->
        <!-- small box -->
        <div class="small-box bg-warning">
          <div class="inner">
            <h3>{{$proses}}</h3>

            <p>Di Proses</p>
          </div>
          <div class="icon">
            <i class="nav-icon fas fa-motorcycle"></i>
          </div>
          <a href="{{ route('donation.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <div class="col-lg-3 col-6"> <!-- berhasil -->
        <!-- small box -->
        <div class="small-box bg-success">
          <div class="inner">
            <h3>{{$berhasil}}</sup></h3>

            <p>Berhasil</p>
          </div>
          <div class="icon">
            <i class="nav-icon fas fa-check"></i>
          </div>
          <a href="{{ route('donation.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
     
      <!-- ./col -->
      <div class="col-lg-3 col-6"> <!-- member -->
        <!-- small box -->
        <div class="small-box bg-danger">
          <div class="inner">
            <h3>{{$members}}</h3>

            <p>Total Member</p>
          </div>
          <div class="icon">
            <i class="nav-icon fas fa-user"></i>
          </div>
          <a href="{{ route('members.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    {{-- <div class="row">
      <!-- Left col -->
      <section class="col-lg-7 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              Sales
            </h3>
            <div class="card-tools">
              <ul class="nav nav-pills ml-auto">
                <li class="nav-item">
                  <a class="nav-link active" href="#revenue-chart" data-toggle="tab">Area</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#sales-chart" data-toggle="tab">Donut</a>
                </li>
              </ul>
            </div>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart"
                   style="position: relative; height: 300px;">
                  <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas>
               </div>
              <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;">
                <canvas id="sales-chart-canvas" height="300" style="height: 300px;"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->

        
      </section>
      <!-- /.Left col -->
      <!-- right col (We are only adding the ID to make the widgets sortable)-->
      <section class="col-lg-5 connectedSortable">

        <!-- Map card -->
        <div class="card bg-gradient-primary">
          <div class="card-header border-0">
            <h3 class="card-title">
              <i class="fas fa-map-marker-alt mr-1"></i>
              Visitors
            </h3>
            <!-- card tools -->
            <div class="card-tools">
              <button type="button" class="btn btn-primary btn-sm daterange" title="Date range">
                <i class="far fa-calendar-alt"></i>
              </button>
              <button type="button" class="btn btn-primary btn-sm" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
            </div>
            <!-- /.card-tools -->
          </div>
          <div class="card-body">
            <div id="world-map" style="height: 250px; width: 100%;"></div>
          </div>
          <!-- /.card-body-->
          <div class="card-footer bg-transparent">
            <div class="row">
              <div class="col-4 text-center">
                <div id="sparkline-1"></div>
                <div class="text-white">Visitors</div>
              </div>
              <!-- ./col -->
              <div class="col-4 text-center">
                <div id="sparkline-2"></div>
                <div class="text-white">Online</div>
              </div>
              <!-- ./col -->
              <div class="col-4 text-center">
                <div id="sparkline-3"></div>
                <div class="text-white">Sales</div>
              </div>
              <!-- ./col -->
            </div>
            <!-- /.row -->
          </div>
        </div>
        <!-- /.card -->

        <!-- solid sales graph -->
        <div class="card bg-gradient-info">
          <div class="card-header border-0">
            <h3 class="card-title">
              <i class="fas fa-th mr-1"></i>
              Sales Graph
            </h3>

            <div class="card-tools">
              <button type="button" class="btn bg-info btn-sm" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn bg-info btn-sm" data-card-widget="remove">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
          <div class="card-body">
            <canvas class="chart" id="line-chart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
          </div>
          <!-- /.card-body -->
          <div class="card-footer bg-transparent">
            <div class="row">
              <div class="col-4 text-center">
                <input type="text" class="knob" data-readonly="true" value="20" data-width="60" data-height="60"
                       data-fgColor="#39CCCC">

                <div class="text-white">Mail-Orders</div>
              </div>
              <!-- ./col -->
              <div class="col-4 text-center">
                <input type="text" class="knob" data-readonly="true" value="50" data-width="60" data-height="60"
                       data-fgColor="#39CCCC">

                <div class="text-white">Online</div>
              </div>
              <!-- ./col -->
              <div class="col-4 text-center">
                <input type="text" class="knob" data-readonly="true" value="30" data-width="60" data-height="60"
                       data-fgColor="#39CCCC">

                <div class="text-white">In-Store</div>
              </div>
              <!-- ./col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.card-footer -->
        </div>
        <!-- /.card -->

        <!-- Calendar -->
        <div class="card bg-gradient-success">
          <div class="card-header border-0">

            <h3 class="card-title">
              <i class="far fa-calendar-alt"></i>
              Calendar
            </h3>
            <!-- tools card -->
            <div class="card-tools">
              <!-- button with a dropdown -->
              <div class="btn-group">
                <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52">
                  <i class="fas fa-bars"></i>
                </button>
                <div class="dropdown-menu" role="menu">
                  <a href="#" class="dropdown-item">Add new event</a>
                  <a href="#" class="dropdown-item">Clear events</a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">View calendar</a>
                </div>
              </div>
              <button type="button" class="btn btn-success btn-sm" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-success btn-sm" data-card-widget="remove">
                <i class="fas fa-times"></i>
              </button>
            </div>
            <!-- /. tools -->
          </div>
          <!-- /.card-header -->
          <div class="card-body pt-0">
            <!--The calendar -->
            <div id="calendar" style="width: 100%"></div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <!-- right col -->
    </div> --}}
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@endsection